"use client";
import { useMemo, useState } from "react";
import Link from "next/link";

type Data = any;
const milestones: Record<number, string> = { 7: "🔥 One week strong!", 30: "🏆 30 days. You've built a habit.", 60: "⚡ 60 days of consistency.", 100: "💯 100 days. Incredible discipline." };
export default function Dashboard({ initial, email }: { initial: Data; email: string }) {
  const [data, setData] = useState<Data>(initial), [showLog, setShowLog] = useState(false), [error, setError] = useState(""), [month, setMonth] = useState(() => { const todayStr = initial?.stats?.today || new Date().toISOString().slice(0, 10); const d = new Date(`${todayStr}T12:00:00`); return isNaN(d.getTime()) ? new Date() : d; });
  const completed = Boolean(data.todayProgress?.completed_at);
  async function refresh() { const r = await fetch("/api/dashboard"); if (r.ok) setData(await r.json()); }
  async function log(form: FormData) { setError(""); const r = await fetch("/api/problems", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), number: form.get("number"), difficulty: form.get("difficulty"), url: form.get("url") }) }); const result = await r.json(); if (!r.ok) return setError(result.error); setShowLog(false); await refresh(); }
  async function signout() { await fetch("/api/auth/logout", { method: "POST" }); location.assign("/login"); }
  async function dismiss() { await fetch(`/api/milestones/${data.celebration}/dismiss`, { method: "POST" }); setData({ ...data, celebration: null }); }
  return <main className="shell"><header className="topbar"><Link className="brand" href="/dashboard">&lt;/&gt; LeetHabit</Link><nav><Link href="/settings">Settings</Link><button className="text-button" onClick={signout}>Sign out</button></nav></header><section className="welcome"><div><p className="eyebrow">DAILY DISCIPLINE</p><h1>Keep the chain alive.</h1><p>{email} · {data.settings.timezone}</p></div><a className="outline-button" href="https://leetcode.com/problemset/" target="_blank">Open LeetCode ↗</a></section>
    {data.celebration && <div className="celebration" role="dialog" aria-label="Milestone achieved"><div><span>NEW MILESTONE</span><strong>{milestones[data.celebration]}</strong></div><button onClick={dismiss} aria-label="Dismiss celebration">×</button></div>}
    <section className="hero-card"><div><p className="eyebrow">TODAY’S GOAL · {data.stats.today}</p><h2>1 <span>problem</span></h2><p className={completed ? "status complete" : "status"}>{completed ? "● Completed" : "● Not completed"}</p></div><button className="primary" onClick={() => setShowLog(true)}>{completed ? "+ Log another problem" : "Solve today’s problem →"}</button></section>
    <section className="stats">{[["Current streak", `${data.stats.current} days`], ["Longest streak", `${data.stats.longest} days`], ["Problems solved", data.stats.totalProblems], ["Completed days", data.stats.completedDays], ["Next milestone", data.stats.nextMilestone ? `${data.stats.nextMilestone} days` : "All reached"]].map(([label, value]) => <article key={String(label)}><small>{label}</small><strong>{value}</strong></article>)}</section>
    <section className="grid"><article className="panel"><div className="panel-heading"><h2>Today’s problems</h2><span>{data.todayProblems.length}</span></div>{data.todayProblems.length ? <div className="problem-list">{data.todayProblems.map((p: any) => <Problem key={p.id} p={p} />)}</div> : <Empty text="Your next solved problem will show up here." />}</article><article className="panel"><div className="panel-heading"><h2>Reminder</h2><span className={data.settings.enabled ? "pill on" : "pill"}>{data.settings.enabled ? "Enabled" : "Paused"}</span></div><p className="reminder-copy">{data.settings.enabled ? `${data.settings.start_time}–${data.settings.cutoff_time} · every ${data.settings.interval_minutes} min` : "No reminders will be sent."}</p><p className="muted">WhatsApp: {data.settings.phone_number ? "connected" : "number not configured"}</p><Link className="inline-link" href="/settings">Configure reminders →</Link></article></section>
    <section className="panel heat"><div className="panel-heading"><h2>Consistency</h2><span>Last 84 days</span></div><Heatmap dates={data.completedDates} today={data.stats.today} /></section>
    <section className="panel calendar"><Calendar dates={data.completedDates} today={data.stats.today} month={month} setMonth={setMonth} /></section>
    <section className="panel"><div className="panel-heading"><h2>Recent activity</h2></div>{data.recent.length ? <div className="activity">{data.recent.map((p: any, i: number) => <div key={`${p.local_date}-${i}`}><time>{p.local_date}</time><Problem p={p} /></div>)}</div> : <Empty text="Start by logging your first problem." />}</section>
    {showLog && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="log-title"><button className="close" onClick={() => setShowLog(false)} aria-label="Close">×</button><p className="eyebrow">TODAY’S WIN</p><h2 id="log-title">Log solved problem</h2><form action={log}><label>Problem name<input name="name" placeholder="Two Sum" required autoFocus /></label><div className="form-grid"><label>Number<input name="number" type="number" min="1" placeholder="1" required /></label><label>Difficulty<select name="difficulty" defaultValue="Easy"><option>Easy</option><option>Medium</option><option>Hard</option></select></label></div><label>LeetCode URL<input name="url" type="url" placeholder="https://leetcode.com/problems/two-sum/" required /></label>{error && <p className="error">{error}</p>}<button className="primary">Mark as solved</button></form></section></div>}
  </main>;
}
function Problem({ p }: { p: any }) { return <div className="problem"><span className={`difficulty ${p.difficulty?.toLowerCase()}`}>{p.difficulty}</span><a href={p.leetcode_url} target="_blank" rel="noreferrer">#{p.problem_number} {p.name} ↗</a>{p.solved_at && <time>{new Date(p.solved_at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}</time>}</div>; }
function Empty({ text }: { text: string }) { return <p className="empty">{text}</p>; }
function Heatmap({ dates, today }: { dates: string[]; today: string }) { const blocks = useMemo(() => { const end = new Date(`${today}T12:00:00Z`), out = []; for (let i = 83; i >= 0; i--) { const d = new Date(end); d.setUTCDate(d.getUTCDate() - i); out.push(d.toISOString().slice(0, 10)); } return out; }, [today]); return <div className="heatmap" aria-label="Completed problem days">{blocks.map(day => <span title={day} key={day} className={dates.includes(day) ? "hit" : ""} />)}</div>; }
function Calendar({ dates, today, month, setMonth }: any) { const y = month.getFullYear(), m = month.getMonth(), first = new Date(y, m, 1), total = new Date(y, m + 1, 0).getDate(), offset = (first.getDay() + 6) % 7; const cells = Array.from({ length: offset + total }, (_, i) => i < offset ? null : i - offset + 1); const dateFor = (n: number) => `${y}-${String(m + 1).padStart(2, "0")}-${String(n).padStart(2, "0")}`; const [selected, setSelected] = useState<string | null>(null); const [problems, setProblems] = useState<any[]>([]); const [loading, setLoading] = useState(false);
  async function selectDay(date: string) { setSelected(date); setLoading(true); setProblems([]); try { const r = await fetch(`/api/calendar/${date}`); if (r.ok) setProblems(await r.json()); } catch {} setLoading(false); }
  return <><div className="panel-heading"><h2>Calendar history</h2><div className="calendar-nav"><button onClick={() => setMonth(new Date(y, m - 1, 1))}>←</button><strong>{month.toLocaleString("default", { month: "long", year: "numeric" })}</strong><button onClick={() => setMonth(new Date(y, m + 1, 1))}>→</button></div></div><div className="weekdays">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((day, i) => !day ? <span key={i} /> : <button key={day} onClick={() => selectDay(dateFor(day))} className={`${dates.includes(dateFor(day)) ? "done" : ""} ${dateFor(day) === today ? "today" : ""}`}><span>{day}</span></button>)}</div>{selected && <div className="selected-day"><strong>{selected}</strong>{loading ? <p className="muted">Loading…</p> : problems.length ? problems.map((p: any, i: number) => <Problem key={i} p={p} />) : <p className="empty">No completed problems recorded.</p>}</div>}</>; }
