"use client";
import Link from "next/link";
import { useState } from "react";
export default function Settings({ initial }: { initial: any }) {
  const [saved, setSaved] = useState(""), [error, setError] = useState(""), [testing, setTesting] = useState(false);
  async function save(form: FormData) { setError(""); setSaved(""); const payload = { enabled: form.get("enabled") === "on", startTime: form.get("startTime"), intervalMinutes: form.get("intervalMinutes"), cutoffTime: form.get("cutoffTime"), timezone: form.get("timezone"), phoneNumber: form.get("phoneNumber") || null, templateName: form.get("templateName"), templateLanguage: form.get("templateLanguage") }; const r = await fetch("/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const d = await r.json(); r.ok ? setSaved("Settings saved.") : setError(d.error); }
  async function test() { setTesting(true); setError(""); const r = await fetch("/api/settings/test", { method: "POST" }), d = await r.json(); setTesting(false); r.ok ? setSaved(d.mockMode ? "Mock test reminder recorded. Add Meta credentials on Render for live delivery." : "Test reminder sent.") : setError(d.error); }
  return <main className="shell narrow"><header className="topbar"><Link className="brand" href="/dashboard">&lt;/&gt; LeetHabit</Link><Link href="/dashboard">← Dashboard</Link></header><section className="settings-head"><p className="eyebrow">PREFERENCES</p><h1>Build your reminder rhythm.</h1><p>Times are interpreted in your chosen timezone. Historical completion dates are preserved.</p></section><form className="settings-form" action={save}><section className="panel"><h2>Daily goal</h2><label>Daily target<input value="1 problem" disabled /></label><p className="muted">A day is complete after your first logged LeetCode problem.</p></section><section className="panel"><h2>Reminders</h2><label className="toggle"><input name="enabled" type="checkbox" defaultChecked={Boolean(initial.enabled)} /><span /> Enable WhatsApp reminders</label><div className="form-grid"><label>Start time<input name="startTime" type="time" defaultValue={initial.start_time} required /></label><label>Cutoff time<input name="cutoffTime" type="time" defaultValue={initial.cutoff_time} required /></label><label>Interval (minutes)<input name="intervalMinutes" type="number" min="15" max="360" defaultValue={initial.interval_minutes} required /></label><label>Timezone<input name="timezone" defaultValue={initial.timezone} placeholder="Asia/Kolkata" required /></label></div></section><section className="panel"><h2>WhatsApp</h2><p className="muted">Credentials stay on the server. Without Meta credentials, testing uses safe mock mode.</p><label>WhatsApp number<input name="phoneNumber" type="tel" defaultValue={initial.phone_number || ""} placeholder="+14155552671" /></label><div className="form-grid"><label>Template name<input name="templateName" defaultValue={initial.template_name} required /></label><label>Template language<input name="templateLanguage" defaultValue={initial.template_language} required /></label></div><button type="button" className="outline-button" onClick={test} disabled={testing}>{testing ? "Sending…" : "Send test reminder"}</button></section>{error && <p className="error" role="alert">{error}</p>}{saved && <p className="success">{saved}</p>}<button className="primary">Save settings</button></form></main>;
}
